openapi: 3.0.0
info: 
  title: "Fmly Landing Page API"
  description: "An API for retaining the email addresses that have signed up for interest in fmly."
  version: "1.0.0"

  servers: 
    - url: "/api"

  paths:
    /waitlist:
      post:
        operationId: "waitlist.post_email"
        tags:
          - "Post_Email"
        summary: "Post email address to waitlist"
        responses:
          "200":
            description: "Successfully joined the waitlist!"
          "400":
            description: "Something went wrong, try again."

      get:
        operationId: "waitlist.get_email"
        tags:
          - "Get_Email"
        summary: "Returns a list of all email addresses who have joined the waitlist."
        responses: 
          "200":
            description: "Here is a list of email addresses on the waitlist" 
          "400":
            description: "Something went wrong, try again."
